### ISSUE TITLE
Look into removing structure.sql from project

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/was-thumbnail-service#20]
There seems to be `db/schema.rb` and `db/structure.rb` checked in for this project. Which one is the authoritative schema for the db?

@jkeck by convention which do we use for other MySQL apps?

**Comment by jkeck** [comment]
`schema.rb` is the convention but `structure.rb` does have its purpose (mainly in describing the database structure in ways that the schema cannot like stored procedures and constraints).  Best I can tell by looking over the migrations there aren't any of these, but I didn't take a close look.

Either way I don't think both should be checked in at the same time.

**Comment by aalsum** [comment]
It's covered by pull request #13
