### ISSUE TITLE
was-thumbnail-stage should connect to swap-stage

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was-thumbnail-service#203]
Currently, [was-thumbnail-stage](https://was-thumbnail-stage.stanford.edu/) is looking at swap in production, so it is not finding data accessioned only in stage.

**Comment by justinlittman** [comment]
This should be done. See https://github.com/sul-dlss/shared_configs/blob/was-thumbnail-service-stage/config/settings/production.yml
