### ISSUE TITLE
issue capturing thumbnail for some sites:  "#FAIL# Unable to load the address! with HTTP status: 200, HTTP message: OK"

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/was-thumbnail-service#216]
see https://app.honeybadger.io/projects/51217/faults/43409116

```
[PROJECT_ROOT]/lib/was/thumbnail_service/capture/capture_thumbnail.rb:21 :in `process_thumbnail`
[PROJECT_ROOT]/lib/was/thumbnail_service/capture/capture_job.rb:11 :in `perform`
[GEM_ROOT]/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81 :in `block in invoke_job`
[GEM_ROOT]/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79 :in `block (2 levels) in add`
[GEM_ROOT]/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61 :in `block in initialize`
[GEM_ROOT]/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79 :in `block in add` 
```

**Describe the bug**

thumbnail capture for some websites fails with this error:
`#FAIL# Unable to load the address! with HTTP status: 200, HTTP message: OK`

e.g.

```
RuntimeError: Thumbnail for memento https://swap.stanford.edu/20170705003503/http://www.thenationalteapartyfederation.com/ can't be generated. #FAIL# Unable to load the address! with HTTP status: 200, HTTP message: OK 
```

the most recent failures:
* http://www.thenationalteapartyfederation.com/
  * this website does seem to be up and responding, though it also seems to be a parked domain based on the current screenshot:  https://urlscan.io/result/b11d64c1-79a4-4089-921d-c791bb232911/
* https://www.marinelepen.fr/
  * this one seems not to be responding to connections:  https://urlscan.io/result/1077bf20-61ad-4b5d-8660-d73c2ccd632e/
    * `Error text of the first response:  net::ERR_CONNECTION_CLOSED`
* http://starwarsgalaxies.station.sony.com/
  * https://urlscan.io/result/scan/ says URL did not resolve

**clarification from andrew:  the thumbnail is hitting SWAP and thumbnailing our representation, not hitting the live site on the general web**

(thanks to one of our info sec channels for showing me urlscan -- i'd be a bit hesitant about hitting the first two of those websites from my own browser these days 😆)

**User Impact**

automatic thumbnail capture does not work reliably for all websites.

**To Reproduce**

**Expected behavior**

**Screenshots**

n/a, see HB links and error text

**Additional context**

**Comment by andrewjbtw** [comment]
I just noticed that this ticket is in the was-thumbnail repo. The way things are named in the WAS workflows is confusing. This issue should be in was_robot_suite since thumbnail-generator is robot step. 

The was-thumbnail-service is not involved in that workflow. The thumbnails it creates are different.

**Comment by andrewjbtw** [comment]
@jmartin-sul I don't seem to be able to close issues in this repo. Could you close now that was-thumbnail is off? Thanks!

**Comment by jmartin-sul** [comment]
> @jmartin-sul I don't seem to be able to close issues in this repo. Could you close now that was-thumbnail is off? Thanks!

weird! closing...

**Comment by jmartin-sul** [comment]
@andrewjbtw i added you as a maintainer to this repo (hopefully just in time for it to be moved to sul-dlss-deprecated 😄)
