### ISSUE TITLE
thumbnail service should create multiple thumbnails for embed

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-thumbnail-service#26]
@nullhandle says "i believe that this is the component that creates the multiple thumbnails for the embed viewer, not the part that creates the single thumbnail that is included in the object" 

"successfully created the single thumbnail, but not (yet anyway) the thumbnails for the embed viewer"  (https://argo-stage.stanford.edu/catalog/druid:hz750bw5867)

It should be part of the workflow (I think it is used by the seed robots somewhere)

**Comment by aalsum** [comment]
Yes, @ndushay , you are right. 

Generating a single thumbnail image for seed object is part of was-seed-preassembly.
https://github.com/sul-dlss/was-seed-preassembly/blob/master/robots/seed/thumbnail_generator.rb

**Comment by drh-stanford** [comment]
Technical diagram for WAS-Thumbnail on Consul:

https://consul.stanford.edu/display/WARC/Web+Archiving+Development+Documentation?preview=/140359302/148604783/Thumbnail%20Service%20Design%20Document.docx

**Comment by ndushay** [comment]
See #29 -- it's too big and is now out of scope for "fix accessioning workflows" milestone.

**Comment by drh-stanford** [comment]
Here's an example of an 3xx error coming back from : https://swap.stanford.edu/20150412231254id_/http://www.noaa.gov/deepwaterhorizon/

**Comment by ndushay** [comment]
I think this may be addressed by the fix for #15 ???

**Comment by ndushay** [comment]
However, I am curious:

- [ ] multiple thumbnails show up in embed, and purl but not in argo contentMetadata?

**Comment by ndushay** [comment]
I am closing this as I believe it is fixed with PR #60.

The bug about redirects is captured as #61
