### ISSUE TITLE
thumbnail service: audit/upgrade/add monitoring (nagios)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-thumbnail-service#46]
going to rails app;  going to new okcomputer mount (so wait for #45, which is waiting for #48)

also migrate to new nagios

also update devops docs

**Comment by tallenaz** [comment]
`newcaprica` has the `was-thumbnail-prod-monitor-log-age` check. do we want to port this to new nagios? what internal and external services should new nagios check?

**Comment by ndushay** [comment]
mailing list is `sul-was-support`

**Comment by ndushay** [comment]
spoke to @nullhandle ;  he is fine with alerts going to opsgenie / on call service etc.
