### ISSUE TITLE
thumbnail service:  use shared configs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-thumbnail-service#48]
- [ ] config info in `config/environments/xxx.rb` should be put in shared_configs.

- [ ] Also have cap deploy automatically grab latest configs -- avail via dlss-capistrano

- [ ] Also update devopsdoc production checklist

**Comment by tallenaz** [comment]
on `was-thumbnail-prod`, see: `/opt/app/was/was-thumbnail-service/shared/config/environments/production.rb`, which has a block of custom config, including pointers to `swap`, 'stacks', and `purl`

**Comment by mjgiarlo** [comment]
Since https://github.com/sul-dlss/was-thumbnail-service/issues/106 was merged, this is now done.
