### ISSUE TITLE
thumbnail:  implement logs retention policy

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-thumbnail-service#49]
do we want to retain any logs?  do we want them on afs?

**Comment by ndushay** [comment]
@nullhandle   do we want these logs to be a 30 day retention with no long term saves also?

**Comment by nullhandle** [comment]
@ndushay I defer to however long you think we need to keep them for troubleshooting purposes. Thirty days seems reasonable.

**Comment by ndushay** [comment]
30 days it is

**Comment by ndushay** [comment]
filed SAR-3344
