### ISSUE TITLE
thumbnail service:  mailing list for admins/maint

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-thumbnail-service#50]
@nullhandle   would this use the same mailing list as the rest?

should be in Devopsdocs and ?nagios?

**Comment by nullhandle** [comment]
@ndushay Yes; all web archiving systems should use the sul-was-support list.

**Comment by ndushay** [comment]
added to puppet

**Comment by ndushay** [comment]
indicated in nagios ticket #46

**Comment by ndushay** [comment]
in devopsdocs with sul-dlss/DevOpsDocs/pull/122
